### Numpy Array Manipulation form the existing data
| Name  | Description | Syntax |
| ------------- | ------------- | ------------- |
| array()  | Create an array.  | array(object[, dtype, copy, order, subok, ndmin]) |
| asarray()  | Convert the input to an array.  | asarray(a[, dtype, order]) |
| asanyarray()  | Convert the input to an ndarray, but pass ndarray subclasses through.  | asanyarray(a[, dtype, order]) |
| ascontiguousarray()  | CReturn a contiguous array in memory (C order).  | ascontiguousarray(a[, dtype]) |
| asmatrix()  | Interpret the input as a matrix.  | asmatrix(data[, dtype]) |
| copy()  | Return an array copy of the given object.  | copy(a[, order] |
| frombuffer()  | Interpret a buffer as a 1-dimensional array. 	  | frombuffer(buffer[, dtype, count, offset]) |
| fromfile()  | Construct an array from data in a text or binary file.  | fromfile(file[, dtype, count, sep]) |
| fromfunction()  | Construct an array from data in a text or binary file.  | fromfile(file[, dtype, count, sep]) |
| fromiter()  |  Create a new 1-dimensional array from an iterable object.  | fromiter(iterable, dtype[, count]) |
| fromstring()   | A new 1-D array initialized from raw binary or text data in a string.  | fromstring(string[, dtype, count, sep]) |
| loadtxt()  | Load data from a text file.  | loadtxt(fname[, dtype, comments, delimiter, ...]) |


#### array() function

The array() function is used to create an array.

Syntax:

numpy.array(object, dtype=None, copy=True, order=’K’, subok=False, ndmin=0)

NumPy array: array() function

In [3]:
import numpy as np
np.array([2, 4, 6])

array([2, 4, 6])

#### asarray() function

The asarray() function is used to convert an given input to an array.

Syntax:

numpy.asarray(a, dtype=None, order=None)

Return value:

[ ndarray] Array interpretation of a. No copy is performed if the input is already an ndarray with matching dtype and order. If a is a subclass of ndarray, a base class ndarray is returned.

Example-1: numpy.asarray() function

In [4]:
import numpy as np
a = [2, 3]
np.asarray(a)

array([2, 3])

#### asanyarray() function

The asanyarray() function is used to convert the input to an ndarray, but pass ndarray subclasses through.

Syntax:

numpy.asanyarray(a, dtype=None, order=None)

In [5]:
import numpy as np
a = [2, 4]
np.asanyarray(a)

array([2, 4])

#### ascontiguousarray() function

The ascontiguousarray() function is used to get a contiguous array in memory (C order).

Syntax:

numpy.ascontiguousarray(a, dtype=None)

In [6]:
import numpy as np
a = np.arange(8). reshape (4, 2)
np.ascontiguousarray(a, dtype=np.float32)

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.]], dtype=float32)

#### asmatrix() function

The asmatrix() function is used to interpret the input as a matrix.
Unlike matrix, asmatrix does not make a copy if the input is already a matrix or an ndarray. Equivalent to matrix(data, copy=False).

Syntax:

numpy.asmatrix(data, dtype=None)

In [7]:
import numpy as np
x = np.array([[1,2], [3,4]])
n = np.asmatrix(x)

| Name  | Description | Required or Optional |
| ------------- | ------------- | ------------- |
| array()  | Create an array.  | array(object[, dtype, copy, order, subok, ndmin]) |
| asarray()  | Convert the input to an array.  | asarray(a[, dtype, order]) |
| asanyarray()  | Convert the input to an ndarray, but pass ndarray subclasses through.  | asanyarray(a[, dtype, order]) |
| ascontiguousarray()  | CReturn a contiguous array in memory (C order).  | ascontiguousarray(a[, dtype]) |
| asmatrix()  | Interpret the input as a matrix.  | asmatrix(data[, dtype]) |