# Numpy Tutorial
----------------
#### Creatin a 1-D array

In [9]:
import numpy as np
l1=[1,2,3,4,5]
arr=np.array
print("displaying the built-in type:- ",arr)
print("Printing the array: -")
print(np.array(l1))

displaying the built-in type:-  <built-in function array>
Printing the array: -
[1 2 3 4 5]


##### Displaying the 2-d array

In [10]:
import numpy as np
l1=[[1,2,3,4,5],
    [1,2,3,4,5]]
print("Printing the array: -")
print(np.array(l1))

Printing the array: -
[[1 2 3 4 5]
 [1 2 3 4 5]]


#### 0-D Arrays

In [11]:
import numpy as np
arr = np.array(42)
print(arr) 

42


#### creating 3-D Array
Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr) 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


#### Check Number of Dimensions?

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

Check how many dimensions the arrays have: