# Numpy Tutorial
----------------
#### Creatin a 1-D array

In [9]:
import numpy as np
l1=[1,2,3,4,5]
arr=np.array
print("displaying the built-in type:- ",arr)
print("Printing the array: -")
print(np.array(l1))

displaying the built-in type:-  <built-in function array>
Printing the array: -
[1 2 3 4 5]


##### Displaying the 2-d array

In [10]:
import numpy as np
l1=[[1,2,3,4,5],
    [1,2,3,4,5]]
print("Printing the array: -")
print(np.array(l1))

Printing the array: -
[[1 2 3 4 5]
 [1 2 3 4 5]]


#### 0-D Arrays

In [11]:
import numpy as np
arr = np.array(42)
print(arr) 

42


#### creating 3-D Array
Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr) 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


#### Check Number of Dimensions?

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

Check how many dimensions the arrays have:

In [13]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


## Higher Dimensional Arrays

An array can have any number of dimensions. When the array is created, you can define the number of dimensions by using the ndmin argument.
Example: Create an array with 5 dimensions and verify that it has 5 dimensions:

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# NumPy Array Indexing

Access Array Elements

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [18]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


Get third and fourth elements from the following array and add them.

In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3]) 

7


Access 2-D Arrays

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the row represents the dimension and the index represents the column.
Example

Access the element on the first row, second column:

In [20]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1]) 

2nd element on 1st row:  2
