# Numpy Tutorial
----------------
#### Creatin a 0-D array

In [12]:
import numpy as np
a = np.array(42)
print(a.ndim," - Dimension")


0  - Dimension


# Numpy Tutorial
----------------
#### Creatin a 1-D array

In [9]:
import numpy as np
l1=[1,2,3,4,5]
arr=np.array
print("displaying the built-in type:- ",arr)
print("Printing the array: -")
print(np.array(l1))

displaying the built-in type:-  <built-in function array>
Printing the array: -
[1 2 3 4 5]


##### Displaying the 2-d array

In [10]:
import numpy as np
l1=[[1,2,3,4,5],
    [1,2,3,4,5]]
print("Printing the array: -")
print(np.array(l1))

Printing the array: -
[[1 2 3 4 5]
 [1 2 3 4 5]]


#### 0-D Arrays

In [11]:
import numpy as np
arr = np.array(42)
print(arr) 

42


#### creating 3-D Array
Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr) 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


#### Check Number of Dimensions?

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

Check how many dimensions the arrays have:

In [22]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


## Higher Dimensional Arrays

An array can have any number of dimensions. When the array is created, you can define the number of dimensions by using the ndmin argument.
Example: Create an array with 5 dimensions and verify that it has 5 dimensions:

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# NumPy Array Indexing

Access Array Elements

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [18]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


Get third and fourth elements from the following array and add them.

In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3]) 

7


Access 2-D Arrays

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the row represents the dimension and the index represents the column.
Example

Access the element on the first row, second column:

In [23]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1]) 

2nd element on 1st row:  2


![p1 image](p1.png)

# NumPy Arrays Datatypes

![p1 image](p2.png)

![p1 image](p3.png)

![p1 image](p4.png)

# Beginning with NumPy
<Span> Fundamentals
After installing NumPy and getting some code to
work, it's time to cover NumPy basics.
The topics we shall cover in this chapter are as
follows:
* Data types
* Array types
* Type conversions
* Array creation
* Indexing
* Slicing
* Shape manipulation<br/>
Before we start, let me make a few remarks
about the code examples in this chapter. The
code snippets in this chapter show input and

NumPy Quick Start, as the interactive Python
shell of choice for scientific computing. The
advantages of IPython are the --pylab switch
that imports many scientific computing Python
packages, including NumPy, and the fact that it
is not necessary to explicitly call the print()
function to display variable values. Other
features include easy parallel computation and
the notebook interface in the form of a
persistent worksheet in a web browser.
However, the source code delivered alongside
the book is a regular Python code that uses
import and print statements. </span>

# Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [2]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


### Higher Dimensional Arrays
An array can have any number of dimensions. When the array is created, you can define the number of dimensions by using the ndmin argument.

In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# NumPy Functions
![p1image](s_Page1.png)
![p1image](s_Page2.png)
![p1image](s_Page3.png)
![p1image](s_Page4.png)

# Array creation routines
![p1image](p5.png)

![p1image](p6.png)

##### empty() function

The empty() function is used to create a new array of given shape and type, without initializing entries.

Syntax: numpy.empty(shape, dtype=float, order='C')

shape 	Shape of the empty array, e.g., (2, 3) or 2. 	Required <br>
dtype 	Desired output data-type for the array, e.g, numpy.int8. Default is numpy.float64. 	optional <br>
order 	Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.
<br/>

Return value:

[ndarray] Array of uninitialized (arbitrary) data of the given shape, dtype, and order. Object arrays will be initialized to None. 

In [21]:
import numpy as np 
np.empty(32)


array([1.20174185e-311, 1.05730048e-321, 0.00000000e+000, 0.00000000e+000,
       1.42413554e-306, 5.02034658e+175, 4.28008993e-033, 1.81451452e-052,
       4.99802905e+174, 2.21608031e-056, 4.04208468e-057, 4.25757514e-096,
       1.12855837e+277, 8.93168725e+271, 7.33723594e+223, 1.70098498e+256,
       5.49109388e-143, 1.06396443e+224, 3.96041428e+246, 1.16318408e-028,
       3.12452929e-033, 7.26782203e-043, 2.37858695e+184, 9.13472925e+169,
       2.24151504e+174, 3.36163259e-067, 5.41977915e-067, 2.42240813e-028,
       1.69177312e-052, 5.74015544e+180, 1.94919988e-153, 1.35679678e-306])

In [22]:
np.empty(2)


array([4.24399158e-314, 8.48798317e-314])

In [23]:
np.empty([2, 2])


array([[7.74860416e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304]])

In [24]:
np.empty([2, 3])

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313],
       [4.24399158e-314, 8.48798317e-314, 1.27319747e-313]])

##### empty_like() function

The empty_like() function is used to create a new array with the same shape and type as a given array.
Syntax: numpy.empty_like(prototype, dtype=None, order='K', subok=True)

Parameter:

prototype: The shape and data-type of prototype define these same attributes of the returned array. 	Required<br/>
dtype :Overrides the data type of the result. 	optional<br/>
order :	Overrides the memory layout of the result. ‘C’ means Corder, ‘F’ means F-order, ‘A’ means ‘F’ if prototype is Fortran contiguous, ‘C’ otherwise. ‘K’ means match the layout of prototype as closely as possible. New in version 1.6.0. 	optional<br/>
subok :	If True, then the newly created array will use the sub-class type of 'a', otherwise it will be a base-class array. Defaults to True. 	optional<br/>

Return value:

[ndarray] Array of uninitialized (arbitrary) data with the same shape and type as prototype

In [25]:
import numpy as np
a = ([1,2,3], [4,5,6])
np.empty_like(a)

array([[ 1400242384,         566,           0],
       [          0,      131074, -2147483648]])

##### eye() function

The eye() function is used to create a 2-D array with ones on the diagonal and zeros elsewhere.

Syntax:

numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Parameter:
Name &nbsp;&nbsp;&nbsp;Description&nbsp;Required / Optional

N &nbsp;Number of rows in the output.&nbsp;Required<br/>
M&nbsp;Number of columns in the output. If None, defaults to N.&nbsp;optional<br/>
k&nbsp;Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.&nbsp;optional<br/>
dtype 	Data-type of the returned array. 	optional
order 	Whether the output should be stored in row-major (C-style) or column-major (Fortran-style) order in memory 	optional

Return value:

[ndarray of shape (N,M)] An array where all elements are equal to zero, except for the k-th diagonal, whose values are equal to one.

In [27]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

##### identity() 	
Return the identity array. 	The identity array is a square array with ones on the main diagonal. The identity() function return the identity array.<br/>
identity(n[, dtype])

In [30]:
np.identity(10)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

##### ones() function

The ones() function is used to get a new array of given shape and type, filled with ones.<br/>

Syntax: numpy.ones(shape, dtype=None, order='C')

In [33]:
np.ones((2, 1))

array([[1.],
       [1.]])

In [36]:
x=2,3
np.ones(x)

array([[1., 1., 1.],
       [1., 1., 1.]])

![p1image](p7.png)
![p1image](p8.png)